# evolve/chassis.py -- frozen copy of candidates/K.py with typed mutation blocks.
# source sha256 c38b582a1380. Rebuild: python3 evolve/blocks.py build
"""K — knob-parameterized V3.12 chassis for discovery search (Sep 2026).

Identical to candidates/V3_12.py except every mutation surface is a KNOBS entry, so
variants are generated by rewriting the KNOBS line only (see gen_variants.py).

Knobs (default = V3.12 behaviour):
  melon_floor   150   sell MELON only at/above this price (0 = sell on arrival)
  harvest_min   2     ongoing crops: harvest when yield_units >= this (1 = every yield)
  opening       "v312" | "frontier"   day-0 orders (frontier = 2c/2s/12 melon/7 wheat/5 hires/5 feed)
  wheat_tiles   0     keep this many WHEAT tiles planted (seeds+plants) through day 24
  wheat_stock   0     hold this much WHEAT in the shed above feed needs until day 27 (sell later, higher)
  min_hands     3
  load_per_hand 20
  geese         0     GOOSE to buy on day 1 (EGG income) — 0 disables
"""
import math
import sys

KNOBS = {"melon_floor": 200, "harvest_min": 2, "opening": "frontier", "wheat_tiles": 0, "wheat_stock": 0, "min_hands": 3, "load_per_hand": 16, "geese": 0, "open_melons": 10, "open_wheat": 8, "open_cows": 2, "open_sheep": 2, "early_hire_days": 5, "feed_spare_poor": 0, "fert_keep": 0, "fert_buy": 0, "fert_carry": 3, "demand_share": 0.5, "max_animals": 20, "wheat_per_animal": 0.0, "wheat_cap": 18, "wheat_water_tier": 1, "wheat_sell_price": 29, "wheat_hold_days": 0, "sell_hourly": 0, "drop_min": 0, "drop_radius": 0, "capital_hour2": -1, "melon_rush": 0, "straw_delay": 0, "hands_early": 0}

BOARD = 10
SHED_TILES = [(4, 4), (5, 4), (4, 5), (5, 5)]
CROPS = {
    "WHEAT":      {"seed": 10,  "first": 2,  "max_day": 4,  "interval": 0, "max_yield": 6, "ongoing": False},
    "CARROT":     {"seed": 20,  "first": 2,  "max_day": 3,  "interval": 0, "max_yield": 4, "ongoing": False},
    "TOMATO":     {"seed": 50,  "first": 8,  "max_day": 8,  "interval": 1, "max_yield": 4, "ongoing": True},
    "STRAWBERRY": {"seed": 100, "first": 10, "max_day": 10, "interval": 2, "max_yield": 4, "ongoing": True},
    "MELON":      {"seed": 80,  "first": 10, "max_day": 12, "interval": 0, "max_yield": 6, "ongoing": False},
}
ANIMALS = {"COW": 400, "SHEEP": 500, "GOOSE": 300}
PRODUCTS = ["MILK", "WOOL", "STRAWBERRY", "FERTILIZER", "MELON", "TOMATO", "CARROT", "EGG", "WHEAT"]
LAND_PRICES = [1000, 2000, 4000]
LAND_DEADLINE = {2: 14, 3: 17, 4: 18}      # quads-after-purchase -> last day
MAX_ORDERS = 10

MAX_ANIMALS = 20
MAX_SHEEP = 12
I0 = 10000
SHOPS = {"BAKERY": ["EGG", "WHEAT"], "PIZZA_SHOP": ["MILK", "TOMATO", "WHEAT"], "BRUNCH_SPOT": ["EGG", "WHEAT", "STRAWBERRY"],
         "YARN_STORE": ["WOOL"], "ICE_CREAM_SHOP": ["STRAWBERRY", "MILK", "WHEAT"], "PET_CAFE": ["CARROT"],
         "SMOOTHIE_SHOP": ["STRAWBERRY", "MILK"], "FARMERS_MARKET": ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY"]}
PRODUCT_OF = {"COW": "MILK", "SHEEP": "WOOL"}
RATE = {"COW": 1.5, "SHEEP": 1.33}           # units/day with daily FEED+CARE (engine: bonus accrues per cared day)
FIRST_YIELD = {"COW": 8, "SHEEP": 6}
DEMAND_SHARE = 0.5                            # my share of daily town demand (two sellers)
OPP_GROWTH = 1.1# opponent's visible supply is assumed to grow
CFG = {"center_interval": 24, "shop_interval": 4, "turns_per_day": 24}
MAX_HANDS = 13
LOAD_ANIMAL, LOAD_CROP_TASK, LOAD_SETUP = 6, 3, 8
ROUTE_LEN = 3
CROP_SWEEP_LEN = 5
CROP_SWEEP_RADIUS = 4
STRAW_CUTOFF = 17
MELON_WAVE_DAYS = ((1, 10),)
MELON_MAX_TILES = 50
MELON_UNITS_PER_TILE = 6.0
MELON_PRICE_CUSHION = 100
OPENING_MELONS = 10
CROP_SPECS = {
    "STRAWBERRY": {"seed": 100, "units": 4.5, "first": 10, "cycle": 18, "cutoff": 17, "base": 120, "min_val": 12},
    "MELON":      {"seed": 80,  "units": 6.0, "first": 10, "cycle": 12, "cutoff": 16, "base": 250, "min_val": 12, "cushion": 100},
    "WHEAT":      {"seed": 10,  "units": 5.0, "first": 2,  "cycle": 5,  "cutoff": 24, "base": 25,  "min_val": 12},
    "CARROT":     {"seed": 20,  "units": 4.0, "first": 2,  "cycle": 4,  "cutoff": 25, "base": 35,  "min_val": 12},
    "TOMATO":     {"seed": 50,  "units": 5.0, "first": 8,  "cycle": 12, "cutoff": 20, "base": 60,  "min_val": 12},
}     # units above I0 before MELON drops from $250 toward $150 (sq curve)
HERD_LAST_DAY = 22
NEAR_RADIUS = 2

# ---- per-episode state (hands are re-indexed daily; everything below is reset at day change)
S = {"day": -1, "routes": {}, "crop": {}, "sweep": {}, "setup": {}, "claimed_sites": set(), "animal_claim": set(),
     "hires_target": 0, "wheat_budget": 0}


def _fib(n):
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def _dist(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def _step(pos, tgt):
    x, y = pos
    tx, ty = tgt
    if x < tx: return "EAST"
    if x > tx: return "WEST"
    if y < ty: return "SOUTH"
    if y > ty: return "NORTH"
    return None


def _shed_dist(pos):
    return min(_dist(pos, t) for t in SHED_TILES)


def _water_needed(t, day):
    cu = t.get("consecutive_unwatered", 0)
    if cu >= 1:
        return "urgent"
    c = CROPS.get(t.get("crop"))
    if not c:
        return None
    pd = t.get("planted_day", day)
    age = day - pd
    if c["ongoing"]:
        step_i = max(1, c["interval"])
        dsf = (day + 1) - pd - c["first"]
        if dsf < 0 or dsf % step_i != 0:
            return None
        if dsf // step_i + 1 > c["max_yield"]:
            return None
        return "water" if t.get("fertilized_until_day", -1) >= day else None
    ws = (c["max_day"] + 1) // 2
    if ws <= age <= c["max_day"] and t.get("yield_units", 0) < c["max_yield"]:
        return "water"
    return None


def _harvest_ready(t, day):
    c = CROPS.get(t.get("crop"))
    if not c:
        return False
    yu = t.get("yield_units", 0)
    age = day - t.get("planted_day", day)
    if yu <= 0:
        return False
    if c["ongoing"]:
        return yu >= KNOBS["harvest_min"] or day >= 18
    if KNOBS["melon_rush"] and t.get("crop") == "MELON" and age >= c["first"] and yu >= 5:
        return True
    return yu >= c["max_yield"] or age >= c["max_day"] or day >= 29


def _fert_eligible(t, day):
    c = CROPS.get(t.get("crop"))
    if not c or not c["ongoing"] or day > 26:
        return False
    age = day - t.get("planted_day", day)
    step_i = max(1, c["interval"])
    done = 0 if age < c["first"] else (age - c["first"]) // step_i + 1
    return done < c["max_yield"] and age >= c["first"] - 1 and t.get("fertilized_until_day", -1) < day


def perceive(obs):
    p = obs["player"]
    me = obs["farms"][p]
    day = obs["day"]
    tiles = me["tiles"]
    v = {"animals": [], "empty_pastures": [], "empty": [], "weeds": [], "crops": [], "shed_tiles": [],
         "unlocked": 0}
    for y in range(BOARD):
        for x in range(BOARD):
            t = tiles[y][x]
            if t == "LOCKED":
                continue
            v["unlocked"] += 1
            if t is None:
                v["empty"].append((x, y))
            elif isinstance(t, dict):
                k = t.get("kind")
                if "animal" in t:
                    v["animals"].append(((x, y), t))
                elif k in ("PASTURE", "COOP"):
                    v["empty_pastures"].append((x, y))
                elif k == "WEED":
                    v["weeds"].append((x, y))
                elif k == "PLANT":
                    v["crops"].append(((x, y), t))
    v["shed_tiles"] = [t for t in SHED_TILES if tiles[t[1]][t[0]] != "LOCKED"]
    v["urgent"] = [pos for pos, t in v["crops"] if not t.get("watered_today") and _water_needed(t, day) == "urgent"]
    v["water"] = [pos for pos, t in v["crops"] if not t.get("watered_today") and _water_needed(t, day) == "water"]
    v["wwater"] = []
    if KNOBS["wheat_water_tier"]:
        v["wwater"] = [pos for pos in v["water"] if tiles[pos[1]][pos[0]].get("crop") == "WHEAT"]
        v["water"] = [pos for pos in v["water"] if pos not in v["wwater"]]
    v["harvest"] = [pos for pos, t in v["crops"] if _harvest_ready(t, day)]
    v["fert"] = [pos for pos, t in v["crops"] if _fert_eligible(t, day)]
    v["slack"] = [pos for pos, t in v["crops"] if not t.get("watered_today") and _water_needed(t, day) is None
                  and CROPS.get(t.get("crop"), {}).get("ongoing")]
    v["tiles"] = tiles
    return v


# ======================================================================
# ECONOMY
# ======================================================================

# ===== EVOLVE-BLOCK: hiring =====
def _hire_plan(target, have, hires_today, cash):
    """Return the affordable hires needed to reach the planner's hand target."""
    n = 0
    spent = 0
    while have + n < target:
        cost = _fib(hires_today + n)
        if spent + cost > cash:
            break
        spent += cost
        n += 1
    return n, spent


def _load_model(v, seeds_planned, n_animals_total, n_setup, day):
    """Conservative headcount for a complete day route (farmer is included)."""
    hard = len(v["urgent"]) + len(v.get("wwater", [])) + n_animals_total
    optional = len(v["water"]) + len(v["harvest"]) + len(v["weeds"]) + seeds_planned
    # A routed hand normally completes 8-10 chores after travel.  Setup is more
    # expensive and planting reserves a second action for same-day watering.
    actions = hard * 2 + optional + seeds_planned + n_setup * 4
    target = max(int(math.ceil(hard / 8.0)), int(math.ceil(actions / 10.0)))
    floor = KNOBS["hands_early"] if KNOBS["hands_early"] and day <= 10 else KNOBS["min_hands"]
    target = max(floor, target)
    if day <= 2:
        target = max(3, target)
    if day >= 29:
        target = min(target, 6)
    return min(MAX_HANDS, target)
# ===== END-BLOCK: hiring =====


MAX_SHOP_INSTANCES = 8
UNLOCK_INTERVAL = 3


# ===== EVOLVE-BLOCK: demand =====
def _instances(obs, item):
    """Unlocked shop instances buying `item` (duplicates count; single-product shops draw double)."""
    n = 0.0
    for name in obs.get("town", {}).get("unlocked_shops", []) or []:
        prods = SHOPS.get(name, [])
        if item in prods:
            n += 2 if len(prods) == 1 else 1
    return n


def _daily_demand(obs, item, day, sell_start=None):
    shops = obs.get("town", {}).get("unlocked_shops", []) or []
    per_day = CFG["turns_per_day"] / max(1, CFG["shop_interval"])
    if sell_start is None:
        sell_start = day
    mid = (sell_start + 29) / 2.0
    slots_by_mid = min(MAX_SHOP_INSTANCES, int(mid // UNLOCK_INTERVAL))
    future = max(0, slots_by_mid - len(shops))
    d = _instances(obs, item) * per_day
    exp_per_slot = sum((2 if len(p) == 1 else 1) for p in SHOPS.values() if item in p) / len(SHOPS)
    d += future * exp_per_slot * per_day
    d += CFG["turns_per_day"] / max(1, CFG["center_interval"])
    return d


def _demand_room(obs, v, species, day, my_count, opp_count):
    item = PRODUCT_OF[species]
    inv = obs["market"]["inventory"].get(item, I0)
    reservoir = max(0.0, I0 - inv)
    T = max(1, 29 - day)
    T_new = max(0, T - FIRST_YIELD[species] - 1)
    if T_new <= 0:
        return 0
    sustainable_rate = KNOBS["demand_share"] * _daily_demand(obs, item, day, day + FIRST_YIELD[species]) + reservoir / T
    n_max = int(sustainable_rate // RATE[species])
    return max(0, n_max - my_count)
# ===== END-BLOCK: demand =====


STRAW_UNITS_PER_TILE = 4.0


# ===== EVOLVE-BLOCK: economy =====
def economy(obs, v):
    p = obs["player"]
    me = obs["farms"][p]
    day, hour = obs["day"], obs["hour"]
    shed = obs["private"]["shed"]
    seeds = obs["private"]["seeds"]
    prices = obs["market"]["prices"]
    cash = me["money"]
    quads = len(me["unlocked_quadrants"])
    orders = []
    n_hands = len(me["hands"])
    inv = obs["private"].get("inventories") or []
    carried_animals = sum(i.get(a, 0) for i in inv for a in ANIMALS)
    shed_animals = sum(shed.get(a, 0) for a in ANIMALS)
    n_active = len(v["animals"])
    n_total = n_active + shed_animals + carried_animals

    # ---- sells (every hour on days >= 28, otherwise hour 0)
    shed_load = sum(n for k, n in shed.items() if k not in ANIMALS and n > 0)
    revenue_est = 0.0
    fert_want = 0
    if day <= 26 and (KNOBS["fert_keep"] > 0 or KNOBS["fert_buy"] > 0):
        fert_want = min(KNOBS["fert_keep"] + KNOBS["fert_buy"], len(v["fert"]))
    if hour == 0 or day >= 28 or KNOBS["sell_hourly"]:
        for item in ("MILK", "WOOL", "STRAWBERRY", "FERTILIZER", "TOMATO", "CARROT", "EGG"):
            n = shed.get(item, 0)
            if item == "FERTILIZER" and day <= 26:
                n = max(0, n - min(KNOBS["fert_keep"], fert_want))
            if n > 0:
                orders.append(["SELL", item, int(n)])
                revenue_est += n * prices.get(item, 0) * 0.85
        n = shed.get("MELON", 0)
        if n > 0 and (prices.get("MELON", 0) >= KNOBS["melon_floor"] or day >= 27 or shed_load > 75):
            orders.append(["SELL", "MELON", int(n)])
            revenue_est += n * prices.get("MELON", 0) * 0.7
        w = shed.get("WHEAT", 0)
        if day >= 29:
            if w > 0:
                orders.append(["SELL", "WHEAT", int(w)])
        elif prices.get("WHEAT", 0) >= (KNOBS["wheat_sell_price"] if day < 27 else 30):
            hold = KNOBS["wheat_stock"] if day < 27 else 0
            reserve_feed = (n_total + 3) + (n_total * KNOBS["wheat_hold_days"] if day < 27 else 0)
            surplus = int(w - reserve_feed - hold)
            if shed_load > 80:
                surplus = int(w - (n_total + 3))
            if surplus > 0:
                orders.append(["SELL", "WHEAT", surplus])
                revenue_est += surplus * prices.get("WHEAT", 0) * 0.9
    capital_hour = 0 if day == 0 else 1          # V3.10: capital decisions on exact post-sale cash at hour 1
    if hour != capital_hour and not (KNOBS["capital_hour2"] >= 0 and hour == KNOBS["capital_hour2"] and day >= 1):
        if hour == 0:
            spare = 3 if cash + revenue_est >= 300 else KNOBS["feed_spare_poor"]
            feed_need = max(0, n_total + spare - shed.get("WHEAT", 0)) if day < 29 else 0
            wheat_cost = feed_need * prices.get("WHEAT", 40) * 1.15
            seeds_on_hand = sum(seeds.get(c, 0) for c in CROP_SPECS)
            target = _load_model(v, seeds_on_hand, n_total, shed_animals + carried_animals, day)
            S["hires_target"] = target
            if day <= KNOBS["early_hire_days"]:
                # labor first: hires cost fib dollars; feed is bought with whatever is left
                n, spent = _hire_plan(target, n_hands, me["hires_today"], max(0.0, cash + revenue_est))
                orders += [["HIRE"]] * max(0, min(n, MAX_ORDERS - len(orders)))
                affordable = int(max(0.0, cash + revenue_est - spent) // (prices.get("WHEAT", 40) * 1.15))
                feed_need = min(feed_need, affordable)
                if feed_need > 0:
                    orders.append(["BUY_PRODUCT", "WHEAT", int(feed_need)])
            else:
                if feed_need > 0:
                    orders.append(["BUY_PRODUCT", "WHEAT", int(feed_need)])
                n, _ = _hire_plan(target, n_hands, me["hires_today"], max(0.0, cash + revenue_est - wheat_cost - 50))
                orders += [["HIRE"]] * max(0, min(n, MAX_ORDERS - len(orders)))
        elif hour <= 2 and day < 30:
            need = S["hires_target"] - n_hands
            if need > 0:
                n, _ = _hire_plan(S["hires_target"], n_hands, me["hires_today"], max(0.0, cash - 50))
                orders += [["HIRE"]] * min(n, MAX_ORDERS - len(orders))
        return orders[:MAX_ORDERS]

    # ---- frontier opening: the whole $3,000 at hour 0 of day 0 (exactly 10 orders)
    if day == 0 and KNOBS["opening"] == "frontier" and n_total == 0:
        S["hires_target"] = 5
        oc, osh, om, ow = KNOBS["open_cows"], KNOBS["open_sheep"], KNOBS["open_melons"], KNOBS["open_wheat"]
        o = [["HIRE"]] * 5
        if oc: o.append(["BUY_ANIMAL", "COW", oc])
        if osh: o.append(["BUY_ANIMAL", "SHEEP", osh])
        if om: o.append(["BUY_SEED", "MELON", om])
        if ow: o.append(["BUY_SEED", "WHEAT", ow])
        o.append(["BUY_PRODUCT", "WHEAT", min(5, oc + osh + 1)])
        return o[:MAX_ORDERS]

    budget = cash + revenue_est
    wheat_price = prices.get("WHEAT", 40)
    feed_need = 0
    if day < 29:
        feed_need = max(0, n_total + 3 - shed.get("WHEAT", 0))
    wheat_cost = feed_need * wheat_price * 1.15
    seeds_on_hand = sum(seeds.get(c, 0) for c in CROP_SPECS)
    target = _load_model(v, seeds_on_hand, n_total, shed_animals + carried_animals, day)
    _, labor_cost_today = _hire_plan(target, n_hands, me["hires_today"], 10 ** 9)
    reserve = wheat_cost + labor_cost_today + 100
    free = budget - reserve

    empty_count = len(v["empty"]) + len(v["empty_pastures"])
    land_wanted = 0

    # ---- herd
    pending_place = shed_animals + carried_animals
    if day == 0 and n_total == 0:
        orders.append(["BUY_ANIMAL", "COW", 1])
        orders.append(["BUY_ANIMAL", "SHEEP", 1])
        free -= 900
        pending_place = 2
        n_total = 2
    elif 1 <= day <= 21 and pending_place <= 3 and n_total < KNOBS["max_animals"]:
        opp = obs["farms"][1 - p]
        opp_counts = {"COW": 0, "SHEEP": 0}
        for row in opp["tiles"]:
            for t in row:
                if isinstance(t, dict) and t.get("animal") in opp_counts:
                    opp_counts[t["animal"]] += 1
        my_counts = {"COW": shed.get("COW", 0), "SHEEP": shed.get("SHEEP", 0), "GOOSE": shed.get("GOOSE", 0)}
        for _pos, t in v["animals"]:
            if t.get("animal") in my_counts:
                my_counts[t["animal"]] += 1
        for i_ in inv:
            for sp in my_counts:
                my_counts[sp] += i_.get(sp, 0)
        _, labor_tomorrow = _hire_plan(target, 0, 0, 10 ** 9)
        income_tomorrow = n_active * prices.get("FERTILIZER", 50) * 0.8
        for i_ in inv:
            for k_, n_ in i_.items():
                if k_ in ("MILK", "WOOL", "STRAWBERRY", "MELON", "EGG", "FERTILIZER"):
                    income_tomorrow += n_ * prices.get(k_, 0) * 0.8
        if KNOBS["geese"] > 0 and day <= 3 and my_counts["GOOSE"] < KNOBS["geese"]:
            k = min(KNOBS["geese"] - my_counts["GOOSE"], int(free // ANIMALS["GOOSE"]))
            if k > 0:
                orders.append(["BUY_ANIMAL", "GOOSE", int(k)])
                free -= ANIMALS["GOOSE"] * k
                n_total += k
                pending_place += k
        for sp in ("SHEEP", "COW"):
            if day > HERD_LAST_DAY and sp == "COW":
                continue
            room = _demand_room(obs, v, sp, day, my_counts[sp], opp_counts[sp])
            if sp == "SHEEP":
                yarn = _instances(obs, "WOOL")
                if yarn == 0:
                    room = min(room, 2 - my_counts[sp])
                elif prices.get("WOOL", 0) >= 1.05 * 200 and day >= 8:
                    room = max(room, 2)
                room = min(room, MAX_SHEEP - my_counts[sp])
            else:
                if _instances(obs, "MILK") == 0 and day >= 9:
                    room = min(room, 4 - my_counts[sp])
            k = min(6, room, KNOBS["max_animals"] - n_total, int(free // ANIMALS[sp]), empty_count - 4)
            while k > 0 and _load_model(v, seeds_on_hand, n_total + k, pending_place + k, day) > MAX_HANDS:
                k -= 1
            while k > 0:
                cash_after = free - ANIMALS[sp] * k + reserve - wheat_cost - labor_cost_today
                need_tomorrow = labor_tomorrow + (n_total + k) * wheat_price - income_tomorrow
                if cash_after >= need_tomorrow:
                    break
                k -= 1
            if k > 0:
                orders.append(["BUY_ANIMAL", sp, int(k)])
                free -= ANIMALS[sp] * k
                n_total += k
                pending_place += k
                my_counts[sp] += k

    # ---- seeds
    if day == 0:
        orders.append(["BUY_SEED", "MELON", OPENING_MELONS])
        free -= 80 * OPENING_MELONS
    else:
        opp = obs["farms"][1 - p]
        committed = {c: 0.0 for c in CROP_SPECS}
        wheat_tiles_now = 0
        for _pos, t in v["crops"]:
            c = t.get("crop")
            if c in committed:
                committed[c] += CROP_SPECS[c]["units"]
            if c == "WHEAT":
                wheat_tiles_now += 1
        for c in committed:
            committed[c] += seeds.get(c, 0) * CROP_SPECS[c]["units"]
        space = empty_count - pending_place - sum(seeds.get(c, 0) for c in CROP_SPECS)
        seed_orders = {}
        n_seed_orders = 0
        excluded = set()
        # ---- wheat tile floor (feed self-supply + late sale)
        wheat_target = max(KNOBS["wheat_tiles"], int(round(KNOBS["wheat_per_animal"] * n_total)))
        wheat_target = min(wheat_target, KNOBS["wheat_cap"])
        if wheat_target > 0 and day <= 24:
            deficit = wheat_target - wheat_tiles_now - seeds.get("WHEAT", 0)
            k = min(deficit, space, int(free // 10))
            if k > 0:
                seed_orders["WHEAT"] = k
                free -= 10 * k
                seeds_on_hand += k
                space -= k
                committed["WHEAT"] += k * CROP_SPECS["WHEAT"]["units"]
                n_seed_orders += 1
                excluded.add("WHEAT")
        while space > 0 and n_seed_orders < 4:
            best = None
            for c, sp_ in CROP_SPECS.items():
                if c in excluded or day > sp_["cutoff"] or day < sp_.get("start", 0):
                    continue
                if c == "STRAWBERRY" and day < KNOBS["straw_delay"]:
                    continue
                T_sell = max(0, 29 - day - sp_["first"])
                if T_sell <= 0:
                    continue
                inv_c = obs["market"]["inventory"].get(c, I0)
                cushion_left = max(0.0, sp_.get("cushion", 0) - max(0.0, inv_c - I0))
                pool = DEMAND_SHARE * (max(0.0, I0 - inv_c) + cushion_left + _daily_demand(obs, c, day, day + sp_["first"]) * (29 - day))
                room_units = pool - committed[c] - seed_orders.get(c, 0) * sp_["units"]
                if room_units < sp_["units"] * 0.5:
                    continue
                price = min(prices.get(c, sp_["base"]), sp_["base"] * 2.0)
                val = min(sp_["units"], room_units) * price / sp_["cycle"]
                if val < sp_["min_val"]:
                    continue
                if best is None or val > best[0]:
                    best = (val, c, room_units)
            if best is None:
                break
            _val, c, room_units = best
            k = min(space, int(room_units // CROP_SPECS[c]["units"]), int(free // CROP_SPECS[c]["seed"]), 20)
            while k > 0 and _load_model(v, seeds_on_hand + k, n_total, pending_place, day) >= MAX_HANDS:
                k -= 1
            if k <= 0:
                excluded.add(c)
                continue
            excluded.add(c)
            seed_orders[c] = seed_orders.get(c, 0) + k
            free -= CROP_SPECS[c]["seed"] * k
            seeds_on_hand += k
            space -= k
            n_seed_orders += 1
            if c == "STRAWBERRY" and room_units // CROP_SPECS[c]["units"] > k + 4:
                land_wanted = int(room_units // CROP_SPECS[c]["units"]) - k
        for c, k in seed_orders.items():
            orders.append(["BUY_SEED", c, int(k)])

    # ---- land
    if quads < 4 and 1 <= day <= LAND_DEADLINE[quads + 1] and empty_count - pending_place < 8 and (land_wanted > 0 or pending_place > empty_count - 2):
        price = LAND_PRICES[quads - 1]
        if quads == 3 and not (day <= 14 and land_wanted >= 12):
            price = float("inf")
        if free >= price:
            orders.append(["BUY_LAND"])
            free -= price

    # ---- wheat feed
    if day < 29:
        feed_need = max(0, n_total + 3 - shed.get("WHEAT", 0) - sum(int(o[2]) for o in orders if o[0] == "BUY_PRODUCT"))
    if feed_need > 0:
        orders.append(["BUY_PRODUCT", "WHEAT", int(feed_need)])

    # ---- fertilizer to apply on ongoing crops (3-day boost doubles the next yields)
    if KNOBS["fert_buy"] > 0 and day <= 26 and len(v["fert"]) > 0:
        fp = prices.get("FERTILIZER", 100)
        eligible = len(v["fert"])
        have = shed.get("FERTILIZER", 0)
        k = min(KNOBS["fert_buy"], max(0, eligible - have), int(max(0.0, free - 50) // max(1, fp)))
        if k > 0 and fp <= 0.6 * prices.get("STRAWBERRY", 120):
            orders.append(["BUY_PRODUCT", "FERTILIZER", int(k)])
            free -= fp * k

    # ---- hires
    target = _load_model(v, seeds_on_hand, n_total, pending_place, day)
    S["hires_target"] = target
    n, _ = _hire_plan(target, n_hands, me["hires_today"], max(0.0, cash + revenue_est - wheat_cost))
    slots = MAX_ORDERS - len(orders)
    orders += [["HIRE"]] * max(0, min(n, slots))
    return orders[:MAX_ORDERS]
# ===== END-BLOCK: economy =====


# ======================================================================
# DISPATCH (unchanged from V3.12)
# ======================================================================

def _nearest(pos, cands):
    best, bd = None, 10 ** 9
    for c in cands:
        d = _dist(pos, c)
        if d < bd:
            best, bd = c, d
    return best


def _animal_pending(t, day):
    if day >= 29:
        return t.get("fertilizer_available", False) or t.get("yield_units", 0) > 0
    need_feed = not t.get("fed_today", False)
    need_care = (not t.get("cared_today", False)) and day < 28
    return need_feed or need_care or t.get("fertilizer_available", False) or t.get("yield_units", 0) > 0


# ===== EVOLVE-BLOCK: animal_routing =====
def _build_route(i, pos, v, day, shed, carry, unlocked_shed, hour=0):
    """Compatibility entry point; routes are built jointly by the dispatcher."""
    plan = S.get("plan")
    if plan and plan.get("day") == day:
        return plan.get("routes", {}).get(i)
    return None


def _route_step(i, pos, v, day, hour, shed, carry, unlocked_shed):
    """Execute one step of a jointly planned route."""
    plan = S.get("plan") or {}
    route = plan.get("routes", {}).get(i)
    if not route:
        return None
    pickup = route.get("pickup", {})
    for item in sorted(pickup):
        need = pickup.get(item, 0)
        have = carry.get(item, 0)
        if need > have:
            if pos not in unlocked_shed:
                return [_step(pos, min(unlocked_shed, key=lambda q: (_dist(pos, q), q)))] if unlocked_shed else None
            n = min(need - have, shed.get(item, 0))
            pickup[item] = have
            if n > 0:
                return ["PICKUP", item, int(n)]
    while route.get("stops"):
        chore = route["stops"][0]
        tp = chore["pos"]
        tile = v["tiles"][tp[1]][tp[0]]
        kind = chore["kind"]
        valid = False
        if kind == "water":
            valid = isinstance(tile, dict) and tile.get("kind") == "PLANT" and not tile.get("watered_today")
        elif kind == "harvest_crop":
            valid = isinstance(tile, dict) and tile.get("kind") == "PLANT" and _harvest_ready(tile, day)
        elif kind == "fertilize":
            valid = carry.get("FERTILIZER", 0) > 0 and isinstance(tile, dict) and _fert_eligible(tile, day)
        elif kind == "plant":
            valid = tile is None and hour < 22 and _plant_choice(tp, plan.get("seeds_left", {})) is not None
        elif kind == "dig":
            valid = isinstance(tile, dict) and tile.get("kind") == "WEED"
        elif kind in ("feed", "care", "collect", "harvest_animal"):
            valid = isinstance(tile, dict) and "animal" in tile
            if kind == "feed": valid = valid and not tile.get("fed_today") and carry.get("WHEAT", 0) > 0
            if kind == "care": valid = valid and day < 28 and not tile.get("cared_today")
            if kind == "collect": valid = valid and tile.get("fertilizer_available", False)
            if kind == "harvest_animal": valid = valid and tile.get("yield_units", 0) > 0
        if not valid:
            route["stops"].pop(0)
            continue
        if pos != tp:
            return [_step(pos, tp)]
        route["stops"].pop(0)
        plan.setdefault("chore_done", set()).add(chore["id"])
        if kind == "water": return ["WATER"]
        if kind in ("harvest_crop", "harvest_animal"): return ["HARVEST"]
        if kind == "fertilize": return ["FERTILIZE"]
        if kind == "dig": return ["DIG"]
        if kind == "feed": return ["FEED"]
        if kind == "care": return ["CARE"]
        if kind == "collect": return ["COLLECT_FERTILIZER"]
        if kind == "plant":
            crop = _plant_choice(tp, plan.get("seeds_left", {}))
            if crop is None:
                continue
            plan["seeds_left"][crop] -= 1
            water = {"id": "water:%d,%d" % tp, "kind": "water", "pos": tp,
                     "deadline": 23, "value": 1000.0, "needs": None, "hard": True}
            route["stops"].insert(0, water)
            return ["PLANT", crop]
    return None
# ===== END-BLOCK: animal_routing =====


# ===== EVOLVE-BLOCK: siting =====
def _pick_site(v, species=None):
    if v["empty_pastures"]:
        c = [s_ for s_ in v["empty_pastures"] if s_ not in S["claimed_sites"]]
        if c:
            return min(c, key=_shed_dist)
    c = [s_ for s_ in v["empty"] if s_ not in S["claimed_sites"] and s_ not in SHED_TILES]
    if not c:
        return None
    return min(c, key=lambda s_: (_shed_dist(s_), s_))


def _setup_step(i, pos, v, carry):
    sp = next((a for a in ANIMALS if carry.get(a, 0) > 0), None)
    if sp is None:
        S["setup"].pop(i, None)
        return None
    site = S["setup"].get(i)
    tiles = v["tiles"]
    want_kind = "COOP" if sp == "GOOSE" else "PASTURE"
    if site is not None:
        t = tiles[site[1]][site[0]]
        ok = t is None or (isinstance(t, dict) and t.get("kind") == want_kind and "animal" not in t)
        if not ok:
            S["claimed_sites"].discard(site)
            site = None
    if site is None:
        if sp == "GOOSE":
            c = [s_ for s_ in v["empty"] if s_ not in S["claimed_sites"] and s_ not in SHED_TILES]
            site = min(c, key=lambda s_: (_shed_dist(s_), s_)) if c else None
        else:
            site = _pick_site(v)
        if site is None:
            return ["PASS"]
        S["setup"][i] = site
        S["claimed_sites"].add(site)
    if pos != site:
        return [_step(pos, site)]
    t = tiles[site[1]][site[0]]
    if t is None:
        return ["BUILD_COOP"] if sp == "GOOSE" else ["BUILD_PASTURE"]
    return ["PLACE", sp]
# ===== END-BLOCK: siting =====


# ===== EVOLVE-BLOCK: crop_admission =====
def _crop_pools(v, seeds_left, day):
    free = [q for q in sorted(v["empty"], key=lambda q: (_shed_dist(q), q)) if q not in S["claimed_sites"]]
    n_rec = seeds_left.get("STRAWBERRY", 0) + seeds_left.get("TOMATO", 0)
    n_one = sum(seeds_left.get(c, 0) for c in CROP_SPECS) - n_rec
    if n_one < 0:
        n_one = 0
    near = [q for q in free if _shed_dist(q) <= NEAR_RADIUS]
    far_left = [q for q in free if _shed_dist(q) > NEAR_RADIUS]
    rec_sites = near[:n_rec]
    near_left = near[n_rec:]
    if len(rec_sites) < n_rec:
        take = n_rec - len(rec_sites)
        rec_sites = rec_sites + far_left[:take]
        far_left = far_left[take:]
    one_sites = far_left[:n_one]
    if len(one_sites) < n_one:
        one_sites = one_sites + near_left[:n_one - len(one_sites)]
    plant = rec_sites + one_sites
    return {"urgent": list(v["urgent"]), "wwater": list(v["wwater"]), "harvest": list(v["harvest"]), "water": list(v["water"]),
            "fert": list(v["fert"]), "plant": plant, "weeds": list(v["weeds"]), "slack": list(v["slack"])}


def _plant_choice(pos, seeds_left):
    d = _shed_dist(pos)
    if d <= NEAR_RADIUS:
        order = ["STRAWBERRY", "TOMATO", "MELON", "CARROT", "WHEAT"]
    elif d <= NEAR_RADIUS + 3:
        order = ["MELON", "CARROT", "WHEAT", "STRAWBERRY", "TOMATO"]
    else:
        order = ["WHEAT", "MELON", "CARROT", "TOMATO", "STRAWBERRY"]
    for c in order:
        if seeds_left.get(c, 0) > 0:
            return c
    return None


def _task_valid(tp, kind, v, day, hour, carry, seeds_left):
    t = v["tiles"][tp[1]][tp[0]]
    if kind in ("urgent", "water", "slack", "wwater"):
        return isinstance(t, dict) and t.get("kind") == "PLANT" and not t.get("watered_today")
    if kind == "harvest":
        return isinstance(t, dict) and t.get("kind") == "PLANT" and t.get("yield_units", 0) > 0
    if kind == "fert":
        return carry.get("FERTILIZER", 0) > 0 and isinstance(t, dict) and _fert_eligible(t, day)
    if kind == "plant":
        return t is None and _plant_choice(tp, seeds_left) is not None and hour < 22
    if kind == "weeds":
        return isinstance(t, dict) and t.get("kind") == "WEED"
    return False
# ===== END-BLOCK: crop_admission =====


# ===== EVOLVE-BLOCK: sweep =====
def _build_sweep(i, pos, v, day, hour, carry, pools, seeds_left):
    """Crop work is represented directly in the shared planner routes."""
    plan = S.get("plan") or {}
    route = plan.get("routes", {}).get(i)
    return route.get("stops") if route else None


def _crop_step(i, pos, v, day, hour, carry, pools, seeds_left):
    # Kept as a block-compatible entry point.  Dispatch calls _route_step so crop
    # and animal actions share one route and one pickup budget.
    return None
# ===== END-BLOCK: sweep =====


# ===== EVOLVE-BLOCK: dispatch =====
def _unit_action(i, pos, carry, obs, v, pools, seeds_left, shed, unlocked_shed):
    day, hour = obs["day"], obs["hour"]

    def chore(kind, tp, value, hard=False, needs=None, deadline=23):
        return {"id": "%s:%d,%d" % (kind, tp[0], tp[1]), "kind": kind, "pos": tp,
                "deadline": deadline, "value": float(value), "needs": needs, "hard": hard}

    def enumerate_all():
        out = []
        prices = obs.get("market", {}).get("prices", {})
        for tp, tile in v["crops"]:
            crop = tile.get("crop")
            spec = CROPS.get(crop, {})
            age = day - tile.get("planted_day", day)
            urgent = tile.get("consecutive_unwatered", 0) >= 1
            in_window = (not spec.get("ongoing") and (spec.get("max_day", 0) + 1) // 2 <= age <= spec.get("max_day", -1)
                         and tile.get("yield_units", 0) < spec.get("max_yield", 0))
            fert_water = spec.get("ongoing") and tile.get("fertilized_until_day", -1) >= day
            if not tile.get("watered_today") and (urgent or in_window or fert_water):
                hard = urgent or (crop == "MELON" and in_window)
                val = 1000 if urgent else prices.get(crop, CROP_SPECS.get(crop, {}).get("base", 40))
                if crop == "MELON" and 6 <= age <= 10:
                    val *= 1.5
                out.append(chore("water", tp, val, hard))
            if _harvest_ready(tile, day):
                out.append(chore("harvest_crop", tp, tile.get("yield_units", 0) * prices.get(crop, 40)))
            if _fert_eligible(tile, day):
                out.append(chore("fertilize", tp, prices.get(crop, 100), False, "FERTILIZER"))
        for tp, tile in v["animals"]:
            animal = tile.get("animal")
            product = PRODUCT_OF.get(animal, "EGG")
            daily = prices.get(product, 100) / max(1.0, 2.0 if animal == "COW" else 3.0 if animal == "SHEEP" else 1.0)
            # The addendum permits alternate-day feed, but never skip a second day.
            if day < 29 and not tile.get("fed_today"):
                # P2 reliability rule: feed every animal before scheduling growth.
                # Alternate-day feeding can return only after zero escapes is proven.
                out.append(chore("feed", tp, daily + prices.get("FERTILIZER", 20), True, "WHEAT"))
            if day < 28 and not tile.get("cared_today"):
                out.append(chore("care", tp, daily))
            if tile.get("fertilizer_available"):
                out.append(chore("collect", tp, prices.get("FERTILIZER", 20)))
            if tile.get("yield_units", 0) > 0:
                out.append(chore("harvest_animal", tp, tile.get("yield_units", 0) * prices.get(product, 100)))
        for tp in v["weeds"]:
            out.append(chore("dig", tp, 10))
        # Late planting has no time to repay its watering burden and was the
        # source of every observed P2 weed (all appeared from day 21 onward).
        for tp in (pools.get("plant", []) if day <= 18 else []):
            crop = _plant_choice(tp, seeds_left)
            if crop:
                spec = CROP_SPECS[crop]
                out.append(chore("plant", tp, spec["base"] * spec["units"] / max(1, spec["cycle"]), False,
                                 "SEED:" + crop, 21))
        return out

    def route_eta(start, stops, needs_pickup):
        cur = start
        total = hour
        if needs_pickup and cur not in unlocked_shed:
            sh = min(unlocked_shed, key=lambda q: (_dist(cur, q), q)) if unlocked_shed else cur
            total += _dist(cur, sh) + 1
            cur = sh
        elif needs_pickup:
            total += 1
        for c in stops:
            total += _dist(cur, c["pos"]) + 1
            if total > c["deadline"]:
                return 99
            cur = c["pos"]
        return total

    def make_plan():
        positions = v["positions"]
        routes = {j: {"unit": j, "stops": [], "pickup": {}, "eta_end": hour} for j in range(len(positions))}
        all_chores = enumerate_all()
        previous = S.get("plan") or {}
        # Chore ids are intentionally position-based, but completion is only a
        # same-day fact.  Carrying this set across days suppresses all recurring
        # feed/water work at those positions.
        done = set(previous.get("chore_done", set())) if previous.get("day") == day else set()
        all_chores = [c for c in all_chores if c["id"] not in done]
        ordered = sorted(all_chores, key=lambda c: (not c["hard"], c["deadline"], -c["value"], c["pos"], c["kind"]))
        unassigned = []
        inventories = obs["private"].get("inventories") or []
        wheat_left = shed.get("WHEAT", 0)
        fert_left = shed.get("FERTILIZER", 0)
        for c in ordered:
            if not c["hard"] and any(x["hard"] for x in unassigned):
                unassigned.append(c)
                continue
            best = None
            # Keep every action at one tile on the same worker.  In particular,
            # animal feed/care/collect/harvest becomes one visit, not four trips.
            owners = [j for j in range(len(positions))
                      if any(x["pos"] == c["pos"] for x in routes[j]["stops"])]
            candidates = owners if owners else list(range(len(positions)))
            for j in candidates:
                inv = inventories[j] if j < len(inventories) else {}
                already = sum(1 for x in routes[j]["stops"] if x["needs"] == c["needs"])
                extra = max(0, already + 1 - inv.get(c["needs"], 0)) - max(0, already - inv.get(c["needs"], 0))
                if c["needs"] == "WHEAT" and extra > wheat_left:
                    continue
                if c["needs"] == "FERTILIZER" and extra > fert_left:
                    continue
                old = routes[j]["stops"]
                for at in range(len(old) + 1):
                    trial = old[:at] + [c] + old[at:]
                    need_pickup = any(x["needs"] in ("WHEAT", "FERTILIZER") for x in trial)
                    eta = route_eta(positions[j], trial, need_pickup)
                    if eta <= c["deadline"] and eta <= 23:
                        key = (eta - routes[j]["eta_end"], eta, j, at)
                        if best is None or key < best[0]: best = (key, j, at, eta)
            if best is None:
                unassigned.append(c); continue
            _key, j, at, eta = best
            routes[j]["stops"].insert(at, c)
            routes[j]["eta_end"] = eta
            if c["needs"] == "WHEAT":
                inv = inventories[j] if j < len(inventories) else {}
                total = sum(1 for x in routes[j]["stops"] if x["needs"] == "WHEAT")
                old_pickup = routes[j]["pickup"].get("WHEAT", 0)
                new_pickup = max(0, total - inv.get("WHEAT", 0))
                routes[j]["pickup"]["WHEAT"] = new_pickup; wheat_left -= new_pickup - old_pickup
            elif c["needs"] == "FERTILIZER":
                inv = inventories[j] if j < len(inventories) else {}
                total = sum(1 for x in routes[j]["stops"] if x["needs"] == "FERTILIZER")
                old_pickup = routes[j]["pickup"].get("FERTILIZER", 0)
                new_pickup = max(0, total - inv.get("FERTILIZER", 0))
                routes[j]["pickup"]["FERTILIZER"] = new_pickup; fert_left -= new_pickup - old_pickup
        return {"day": day, "hour": hour, "routes": routes, "unassigned": unassigned,
                "chore_done": done, "seeds_left": dict(seeds_left),
                "replans": (previous.get("replans", 0) + 1) if previous.get("day") == day else 1,
                "replan_hours": set(previous.get("replan_hours", set())) if previous.get("day") == day else set()}

    if any(carry.get(a, 0) > 0 for a in ANIMALS):
        op = _setup_step(i, pos, v, carry)
        if op is not None: return op
    prod_carried = sum(carry.get(k, 0) for k in PRODUCTS if k != "WHEAT")
    if day >= 28 and prod_carried >= (3 if day == 29 else 6):
        if pos in unlocked_shed: return ["DROP"]
        if day == 29 or hour >= 18: return [_step(pos, min(unlocked_shed, key=lambda q: (_dist(pos, q), q)))]

    plan = S.get("plan")
    if not plan or plan.get("day") != day or (hour == 1 and plan.get("hour") != 1):
        S["plan"] = make_plan()
    op = _route_step(i, pos, v, day, hour, shed, carry, unlocked_shed)
    if op is not None: return op
    plan = S.get("plan") or {}
    pending = set(c["id"] for r in plan.get("routes", {}).values() for c in r.get("stops", []))
    missing_hard = [c for c in enumerate_all() if c["hard"] and c["id"] not in pending
                    and c["id"] not in plan.get("chore_done", set())]
    if missing_hard and plan.get("replans", 0) < 4 and hour not in plan.get("replan_hours", set()):
        old_done = set(plan.get("chore_done", set()))
        old_hours = set(plan.get("replan_hours", set())); old_hours.add(hour)
        S["plan"] = make_plan()
        S["plan"]["chore_done"].update(old_done)
        S["plan"]["replan_hours"] = old_hours
        op = _route_step(i, pos, v, day, hour, shed, carry, unlocked_shed)
        if op is not None: return op
    # Install purchased animals before accepting optional overflow work.
    shed_animals = sorted((a, n) for a, n in shed.items() if a in ANIMALS and n > 0)
    if shed_animals and hour >= 1 and day < 27:
        if pos in unlocked_shed:
            return ["PICKUP", shed_animals[0][0], 1]
        return [_step(pos, min(unlocked_shed, key=lambda q: (_dist(pos, q), q)))]
    if prod_carried >= 4 and carry.get("WHEAT", 0) == 0 and _shed_dist(pos) <= 2:
        if pos in unlocked_shed: return ["DROP"]
        return [_step(pos, min(unlocked_shed, key=lambda q: (_dist(pos, q), q)))]
    return ["PASS"]
# ===== END-BLOCK: dispatch =====


def _agent(obs):
    p = obs["player"]
    me = obs["farms"][p]
    day, hour = obs["day"], obs["hour"]
    if S["day"] != day:
        S.update({"day": day, "routes": {}, "crop": {}, "sweep": {}, "setup": {}, "claimed_sites": set(), "animal_claim": set(), "fert_taken": 0})
    v = perceive(obs)
    shed = obs["private"]["shed"]
    seeds_left = dict(obs["private"]["seeds"])
    inv = obs["private"].get("inventories") or []
    unlocked_shed = v["shed_tiles"]
    market = economy(obs, v)
    reserved = sum(r.get("pickup", 0) for r in S["routes"].values())
    S["wheat_budget"] = max(0, shed.get("WHEAT", 0) - reserved)
    pools = _crop_pools(v, seeds_left, day)
    for sw in S["sweep"].values():
        for tp, kind in sw:
            if kind in pools and tp in pools[kind]:
                pools[kind].remove(tp)
    n_units = 1 + len(me["hands"])
    for d in (S["routes"], S["crop"], S["sweep"], S["setup"]):
        for j in [j for j in d if j >= n_units]:
            d.pop(j, None)
    positions = [tuple(me["farmer"])] + [tuple(h) for h in me["hands"]]
    v["positions"] = positions
    ops = []
    for i, pos in enumerate(positions):
        carry = inv[i] if i < len(inv) else {}
        ops.append(_unit_action(i, pos, carry, obs, v, pools, seeds_left, shed, unlocked_shed))
    return {"farmer": ops[0], "hands": ops[1:], "market": market}


def agent(obs, configuration=None):
    try:
        if configuration is not None:
            g = lambda k, d: (configuration.get(k, d) if isinstance(configuration, dict) else getattr(configuration, k, d))
            CFG["center_interval"] = int(g("townCenterSellInterval", 24)); CFG["shop_interval"] = int(g("townShopSellInterval", 4))
            CFG["turns_per_day"] = int(g("turnsPerDay", 24))
        return _agent(obs)
    except Exception as exc:  # crash guard
        import traceback
        print(f"GUARD swallowed exception: {exc!r}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return {"farmer": ["PASS"], "hands": [], "market": []}
