#!/usr/bin/env python3
"""Build a replay-tape opponent from a recorded Kaggle episode.

The top of the public ladder is largely *tape agents*: the public notebooks
"Kaggriculture | 2900+", "V16-RC5 ...", "84/84 ... V14 Clone Preemption" all ship a
720-entry `_ACTIONS` list (zlib+b85) and replay it turn by turn. This script makes
the same kind of agent from any replay in Replays/, for either seat, so the local
evaluator can face exactly what the ladder fields.

Usage:
  python3 make_tape_agent.py Replays/Auto/leaderboard-Yuan800/episode-104892947-replay.json 1 \
      -o Opponents/tape_yuan800_104892947.py

Verify with mini_engine + replay_verify (a tape vs. the other seat's tape must
reproduce the recorded money exactly).
"""
import argparse
import base64
import json
import zlib
from pathlib import Path

TEMPLATE = '''# Replay-tape agent generated by make_tape_agent.py
# source episode {episode}  seat {seat}  player "{player}"  recorded final money {money}
# opponent in source game: "{opp}"  seed {seed}
import base64, json, zlib

_ACTIONS = json.loads(zlib.decompress(base64.b85decode({blob!r})).decode("utf-8"))


def agent(obs, configuration=None):
    step = obs.get("step") if isinstance(obs, dict) else getattr(obs, "step", None)
    if step is None:
        day = obs["day"] if isinstance(obs, dict) else obs.day
        hour = obs["hour"] if isinstance(obs, dict) else obs.hour
        step = day * 24 + hour
    if 0 <= step < len(_ACTIONS):
        return _ACTIONS[step]
    return {{"farmer": ["PASS"], "hands": [], "market": []}}
'''


def build(replay_path, seat, out):
    d = json.load(open(replay_path))
    steps = d["steps"]
    # action recorded at steps[k+1][seat] is the action taken from state k
    actions = []
    for k in range(1, len(steps)):
        a = steps[k][seat].get("action") or {}
        actions.append({"farmer": a.get("farmer", ["PASS"]), "hands": a.get("hands", []), "market": a.get("market", [])})
    blob = base64.b85encode(zlib.compress(json.dumps(actions, separators=(",", ":")).encode(), 9)).decode()
    names = d["info"].get("TeamNames", ["?", "?"])
    src = TEMPLATE.format(episode=d["info"].get("EpisodeId"), seat=seat, player=names[seat],
                          money=d["rewards"][seat], opp=names[1 - seat], seed=d["info"].get("seed"), blob=blob)
    Path(out).write_text(src)
    return len(actions)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("replay")
    p.add_argument("seat", type=int)
    p.add_argument("-o", "--out", required=True)
    a = p.parse_args()
    n = build(a.replay, a.seat, a.out)
    print(f"wrote {a.out} with {n} actions")


if __name__ == "__main__":
    main()
