#!/usr/bin/env python3
"""Build the flat, single-file Kaggle submission main.py for adaptive-v0.3.

Kaggle's sandbox does not expose sibling files at game time (this is exactly
why v0.2's FIRST ladder submission attempt, 56200346, failed at the
Validation Episode stage -- see
artifacts/ladder_adaptive_v0.2_diagnostic_2026-09-13/derived/LADDER_ADAPTIVE_V0_2_RAW_EVIDENCE.md
section 1). v0.2's fix (submission v2, 56200714) was to inline O42, the
controller, and the frozen learner state into one flat main.py. This script
reproduces that same inlining approach for v0.3, changing nothing about the
method -- only pointing it at the v0.3 controller (with the MIN_N_TO_TRUST_B
guard) instead of the v0.2 controller.

This script performs NO learning, NO A/B tuning, and does not modify O42's
source (only a mechanical top-level name rename, agent -> _o42_agent, to
avoid a Kaggle entrypoint collision -- the exact same rename v0.2 used).
"""
from __future__ import annotations

import base64
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
O42_PATH = REPO_ROOT / "candidates" / "O42_MAX_HANDS_LATE_EXPAND.py"
CONTROLLER_PATH = HERE / "controller" / "adaptive_slice_v0.py"
LEARNER_STATE_PATH = HERE / "state" / "learner_frozen.json"
OUT_PATH = HERE / "main.py"

EXPECTED_O42_SHA256 = "154d1ff480e9aa05084e323604a1a09ce73b68adbff95dd4f410e6acf4f52813"


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def main() -> None:
    o42_src = O42_PATH.read_bytes()
    actual_o42_hash = sha256_bytes(o42_src)
    if actual_o42_hash != EXPECTED_O42_SHA256:
        raise SystemExit(f"REFUSING TO BUILD: O42 hash mismatch (expected {EXPECTED_O42_SHA256}, got {actual_o42_hash})")

    controller_src = CONTROLLER_PATH.read_text()
    # Extract only the pieces the runtime needs (Learner, WrappedAgent, regime,
    # state_vector, apply_variant, animal_orders, VARIANTS, MIN_N_TO_TRUST_B,
    # REWARD_TURNS, stable_hash) -- drop the CLI/runner-only main()/run_game()
    # machinery, which imports kaggle_environments directly and is not needed
    # (and would not run) inside the Kaggle submission sandbox itself.
    cut_marker = "\ndef run_game("
    idx = controller_src.index(cut_marker)
    controller_runtime_src = controller_src[:idx]

    o42_src_renamed = o42_src.decode().replace("def agent(", "def _o42_agent(", 1)
    o42_b64 = base64.b64encode(o42_src_renamed.encode()).decode()
    controller_b64 = base64.b64encode(controller_runtime_src.encode()).decode()
    learner_state = json.loads(LEARNER_STATE_PATH.read_text())
    learner_state_hash = hashlib.sha256(
        json.dumps(learner_state, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    controller_hash = sha256_bytes(controller_src.encode())

    main_py = f'''"""Adaptive v0.3 ladder submission -- flat single-file build.

Generated by candidate/adaptive-v0.3-ladder-candidate/build_submission.py.
Embeds, byte-for-byte: (1) O42 source (base64, entrypoint renamed
agent -> _o42_agent only), (2) the v0.3 controller runtime (verbatim, includes
the MIN_N_TO_TRUST_B=10 guard -- the only change from v0.2), (3) the v0.2
frozen learner state (unchanged, no retraining). Fails closed (SystemExit) at
import time if any embedded content's hash has drifted from what was recorded
at build time below.

O42_SHA256 (pre-embed, of the original file): {actual_o42_hash}
CONTROLLER_SHA256 (of candidate controller file, pre-extraction): {controller_hash}
LEARNER_STATE_SHA256 (of re-serialized frozen state, sort_keys+compact): {learner_state_hash}
"""
import base64
import hashlib
import json

_O42_B64 = "{o42_b64}"
_CONTROLLER_B64 = "{controller_b64}"
_LEARNER_STATE = {json.dumps(learner_state, sort_keys=True)}

_EXPECTED_O42_SHA256 = "{actual_o42_hash}"
_EXPECTED_LEARNER_STATE_SHA256 = "{learner_state_hash}"

_o42_src = base64.b64decode(_O42_B64).decode()
# _o42_src has the mechanical `def agent(` -> `def _o42_agent(` rename already applied at
# build time; reverse it before hashing so this matches _EXPECTED_O42_SHA256, which is the
# hash of the ORIGINAL, unmodified O42 file (the file this candidate is not allowed to alter).
_o42_hash = hashlib.sha256(_o42_src.replace("def _o42_agent(", "def agent(", 1).encode()).hexdigest()
if _o42_hash != _EXPECTED_O42_SHA256:
    raise SystemExit(f"FAIL-CLOSED: embedded O42 hash mismatch (expected {{_EXPECTED_O42_SHA256}}, got {{_o42_hash}})")

_learner_state_hash = hashlib.sha256(json.dumps(_LEARNER_STATE, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
if _learner_state_hash != _EXPECTED_LEARNER_STATE_SHA256:
    raise SystemExit(f"FAIL-CLOSED: embedded learner state hash mismatch (expected {{_EXPECTED_LEARNER_STATE_SHA256}}, got {{_learner_state_hash}})")

# --- O42 (renamed entrypoint only: agent -> _o42_agent; rename applied at build time) ---
exec(compile(_o42_src, "<o42_embedded>", "exec"))

# --- Controller runtime (verbatim v0.3 extract, includes MIN_N_TO_TRUST_B) ---
_controller_src = base64.b64decode(_CONTROLLER_B64).decode()
_controller_hash = hashlib.sha256(_controller_src.encode()).hexdigest()
exec(compile(_controller_src, "<controller_embedded>", "exec"))

# --- Frozen learner (byte-identical to v0.2; no retraining) ---
_learner = Learner()
for _regime, _arms in _LEARNER_STATE.items():
    for _arm, _stat in _arms.items():
        _learner.stats[_regime][_arm]["n"] = _stat["n"]
        _learner.stats[_regime][_arm]["mean"] = _stat["mean"]

_events = []
_wrapped = WrappedAgent(_o42_agent, _learner, "adaptive_frozen", {{"game_id": "ladder", "seed": None, "opponent": "unknown", "seat": None}}, _events)


def agent(obs, cfg):
    return _wrapped(obs, cfg)
'''
    OUT_PATH.write_text(main_py)
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")
    print(f"main.py sha256: {sha256_bytes(OUT_PATH.read_bytes())}")


if __name__ == "__main__":
    main()
